### ISSUE TITLE
nvidia hardware transcoding

### ISSUE THREAD

**Issue by StoragePirate** [comio/plex-overlay#10]
The USE flag "uvm" must be used, if you want to use the nvidia-drivers for hardware encoding. Keep in mind, you still require the plex pass.

**Comment by comio** [comment]
Hi @StoragePirate 

I'm sorry, but I don't understand your suggestion.

Are suggesting to add something like:

```
uvm? ( >=virtual/opencl-3 )
```

to plex server ebuild?

**Comment by StoragePirate** [comment]
> [ebuild   R    ] x11-drivers/nvidia-drivers-440.82-r3:0/440::gentoo  USE="X driver kms multilib tools **uvm** -acpi -compat -gtk3 -libglvnd -static-libs -wayland" ABI_X86="(64) -32 (-x32)" 0 KiB


I had to set the `uvm` flag to get hardware encoding to work.

**Comment by comio** [comment]
I'm closing because nvidia is not officially supported.
