### ISSUE TITLE
Checksum/verification failure on web-client-desktop-4.29.2-e50e175.tar.xz

### ISSUE THREAD

**Issue by Spacexplosion** [comio/plex-overlay#11]
Emerge attempts terminate with the following error:

> &gt;&gt;&gt; Downloading 'https://artifacts.plex.tv/web-client-pmp/182-13c4ebbe50e175/web-client-desktop-4.29.2-e50e175.tar.xz'

...

> 2020-05-13 02:20:41 (5.65 MB/s) - ‘/usr/portage/distfiles/web-client-desktop-4.29.2-e50e175.tar.xz.__download__’ saved [4063292/4063292]
> 
> !!! Fetched file: web-client-desktop-4.29.2-e50e175.tar.xz VERIFY FAILED!
> !!! Reason: Filesize does not match recorded size
> !!! Got:      4063292
> !!! Expected: 4065240
> Refetching... File renamed to '/usr/portage/distfiles/web-client-desktop-4.29.2-e50e175.tar.xz._checksum_failure_.3pt_20hn'
> 
> !!! Couldn't download 'web-client-desktop-4.29.2-e50e175.tar.xz'. Aborting.

**Comment by comio** [comment]
I generate (again) the Manifest. The Plex' guys refreshed the binary blobs...

**Comment by Spacexplosion** [comment]
Looks like it changed but still isn't happy.

> !!! Fetched file: web-client-desktop-4.29.2-e50e175.tar.xz VERIFY FAILED!
> !!! Reason: Filesize does not match recorded size
> !!! Got:      4063292
> !!! Expected: 4061076

**Comment by comio** [comment]
```
while (1) {
  I generate (again) the Manifest. The Plex' guys refreshed the binary blobs...
}
```

**Comment by Spacexplosion** [comment]
Tell me if I'm wrong, but doesn't the "Got" number refer to the real file size of the blob? So it looks like the file size didn't change between my two tries, only the manifest changed to another incorrect value, no?
