### ISSUE TITLE
media-tv/plex-media-server Is masked

### ISSUE THREAD

**Issue by TheGreatMcPain** [comio/plex-overlay#13]
The ebuild on the official gentoo overlay is being removed, because it uses a bundled version of python2.7. See: [Bug #735396](https://bugs.gentoo.org/735396)

The workaround is to unmask it via `package.unmask`.

[Luckily upstream is working on porting all of the python code to C++.](https://forums.plex.tv/t/when-will-plex-media-server-shift-to-python-3/600689/8)

**Comment by anthonyryan1** [comment]
The upstream discussion on this is rather interesting. They've got some feedback for us now.

I don't see the Gentoo lastrites being cancelled, since Gentoo tends to not like packages that bundle all their dependencies like Plex does. But we can and should take their advice on packaging Plex better outside the tree.

Key points from their developers:
- Plex doesn't depend on system python. We should stop trying to use it.
- We should also stop modifying their internal python, it's bizarre and that's expected.

**Comment by TheGreatMcPain** [comment]
Yeah, I was wondering for the longest time why Gentoo's `plex-media-server` ebuild required python as a dependency, because Plex uses a bundled interpreter anyway.

I might try to modify the ebuild in this repository to see if I could install it without the `python2.7` dependency.

**Comment by witcheslive** [comment]
I am not fully clear on the steps required to switch from using the old gentoo ebuild to this overlay, and if anyone passing through has a couple of minutes to put down the steps for what to do, I would greatly appreciate it!

**Comment by anthonyryan1** [comment]
Edit `/etc/portage/package.unmask` and add this line:
```
media-tv/plex-media-server::plex-overlay
```

Edit `/etc/portage/repos.conf` to add these lines:
```
[plex-overlay]
location = /var/db/repos/plex-overlay
sync-type = git
sync-uri = https://github.com/comio/plex-overlay
auto-sync = yes
```

**Comment by TheGreatMcPain** [comment]
@witcheslive Okay, so if your getting an error about `plex-media-server` being masked all you need to do is unmask it like this.

```
# echo "media-tv/plex-media-server::plex-overlay" >> /etc/portage/package.unmask/plex-media-server
```

If it complains about a missing `package.unmask` directory just create it.

```
# mkdir /etc/portage/package.unmask

# touch /etc/portage/package.unmask/zzz_autounmask
```

If it also needs to be in `package.accept_keywords` do this.

```
# echo "media-tv/plex-media-server::plex-overlay ~amd64" >> /etc/portage/package.accept_keywords/plex-media-server
```

The `touch` command is there in-case you want to use the `--autounmask y` option for `emerge` which can be used to automatically create entries in `package.unmask`, `package.accept_keywords, and 'package.use'.

**Comment by saboya** [comment]
So, unmasking it is easy, but right now it's impossible to install this ebuild because Gentoo hard dropped python 2.7, so I get this:

```
emerge: there are no ebuilds to satisfy "dev-python/virtualenv[python_targets_python2_7(-)]".
```

When trying to emerge `plex-media-server`.

**Comment by TheGreatMcPain** [comment]
@saboya Yeah, I just noticed that today.  Looks like this overlay might have add virtualenv with python2 support, or just start using [Plex's builtin python interpreter](https://github.com/comio/plex-overlay/pull/14).

**Comment by TheGreatMcPain** [comment]
Looks like pull 14 got merged, so I guess we can close this issue for now.

**Comment by comio** [comment]
Not merged, but adapted.

**Comment by Peter-Levine** [comment]
> 
> [Luckily upstream is working on porting all of the python code to C++.](https://forums.plex.tv/t/when-will-plex-media-server-shift-to-python-3/600689/8)

I started that Plex thread.  The post about the C++ port was from July 8th but I don't see it anymore.  It looks like it was deleted.

**Comment by TheGreatMcPain** [comment]
Yeah, I noticed that too.
