### ISSUE TITLE
Removal of python2

### ISSUE THREAD

**Issue by Peter-Levine** [comio/plex-overlay#18]
Since the Plex devs have [no intention](https://forums.plex.tv/t/when-will-plex-media-server-shift-to-python-3) of shifting to Python 3 and since Plex is masked for [removal from portage](https://bugs.gentoo.org/735396), eventually with Python 2, itself,  is there and plan to eventually un-unbundle python2 from the plex-media-server ebuilds and remove it as a dependency?

**Comment by TheGreatMcPain** [comment]
Take a look at Issue #13.

The gist is that the devs are porting the python code to C++.

Also, the ebuild in this overlay has shifted to just using Plex's builtin Python interpreter.
