### ISSUE TITLE
Is python needed?

### ISSUE THREAD

**Issue by Gatak** [comio/plex-overlay#2]
Is python use flags/dependencies needed with plex? It uses it's own Python binaries anyway.

**Comment by comio** [comment]
Hi @Gatak,

I think that you are right. I started from portage version and still I don't know why we include python stuffs.
I will modify in the next release.

**Comment by torre76** [comment]
Also, not completely related to this issue, but a complain to Plex devs, their choice causes fkmclane/overlay#88.

And I think it is not possible to link Python used by Plex with the standard one used by Gentoo because of Virtual environments (dependencies) PMS uses...

**Comment by Gatak** [comment]
I did try to see if it was possible to replace the built-in python and ffmpeg/libavcodec with the system one so my own optimised versions would be used. I failed quite badly at that. The stuff is likely hardcoded in plex =(

**Comment by comio** [comment]
Removed pyhon deps

**Comment by dklempner** [comment]
I know this was closed in the past, but as I understand it there was a more recent merge (https://github.com/comio/plex-overlay/pull/5) that undid the removal.

That's particularly a problem right now -- it's blocking upgrades that drop python2 support, and without plex-media-server in the main repo those transitive deps are going to start breaking.
