### ISSUE TITLE
Plex 1.21 fails to merge

### ISSUE THREAD

**Issue by FnordMan** [comio/plex-overlay#20]
Attached build.log, upgrading from 1.20.4. Looks like it's failing a patch? Let me know if you need anything else. 
[build.log](https://github.com/comio/plex-overlay/files/5567820/build.log)

**Comment by TheGreatMcPain** [comment]
Can confirm.

Looks like the patch for plexmediaserver.service needs to be updated.

**Comment by ataferner** [comment]
Confirming this. I have the same problem.

**Comment by j4m35** [comment]
Hi @comio the pull request which you just merged made changes to plex-media-server-1.21.0.ebuild; thus the changes to use the new service patch file is not applied to your plex-media-server-1.21.0-r1.ebuild.

Hence your ebuild will not build as it is still trying to apply the old service patch file.
