### ISSUE TITLE
Install fails on x86

### ISSUE THREAD

**Issue by rugubara** [comio/plex-overlay#23]

**Comment by rugubara** [comment]
The included patch failed to apply

home64 ~ # less /var/tmp/portage/media-tv/plex-media-server-1.21.0/work/usr/lib/plexmediaserver/lib/plexmediaserver.service.rej



--- usr/lib/plexmediaserver/lib/plexmediaserver.service.old     2020-01-29 08:50:39.856491924 +0100
+++ usr/lib/plexmediaserver/lib/plexmediaserver.service 2020-01-29 08:51:49.068249688 +0100
@@ -12,7 +12,8 @@
 export PLEX_MEDIA_SERVER_INFO_VENDOR="$(grep ^NAME= /etc/os-release | awk -F= "{print \\$2}" | tr -d \\" )"; \
 export PLEX_MEDIA_SERVER_INFO_DEVICE="PC"; \
 export PLEX_MEDIA_SERVER_INFO_MODEL="$(uname -m)"; \
-export PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION="$(grep ^VERSION= /etc/os-release | awk -F= "{print \\$2}" | tr -d \\" )"; \
+export GENTOO_PROFILE="`readlink /etc/portage/make.profile`"; \
+export PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION="$${GENTOO_PROFILE#.*/profiles/}"; \
 export LD_LIBRARY_PATH=/usr/lib/plexmediaserver/lib; \
 exec "/usr/lib/plexmediaserver/Plex Media Server"'
 Type=simple
~

**Comment by j4m35** [comment]
The error comes from the following line:
```export LD_LIBRARY_PATH=/usr/lib/plexmediaserver/lib;```

which is not present in the original plexmediaserver.service file.

**Comment by Bigun** [comment]
>>> Emerging (1 of 1) media-tv/plex-media-server-1.21.0-r1::plex-overlay
 * plexmediaserver_1.21.0.3608-f7262c352_i386.deb BLAKE2B SHA512 size ;-) ...                                                                                                                           [ ok ]
>>> Unpacking source...
>>> Unpacking plexmediaserver_1.21.0.3608-f7262c352_i386.deb to /var/tmp/portage/media-tv/plex-media-server-1.21.0-r1/work
>>> Unpacking data.tar.xz to /var/tmp/portage/media-tv/plex-media-server-1.21.0-r1/work
>>> Source unpacked in /var/tmp/portage/media-tv/plex-media-server-1.21.0-r1/work
>>> Preparing source in /var/tmp/portage/media-tv/plex-media-server-1.21.0-r1/work ...
 * Applying plexmediamanager.desktop.new.patch ...                                                                                                                                                      [ ok ]
 * Applying plexmediaserver.service.patch ...
patching file usr/lib/plexmediaserver/lib/plexmediaserver.service
Hunk #1 FAILED at 27.
1 out of 1 hunk FAILED -- saving rejects to file usr/lib/plexmediaserver/lib/plexmediaserver.service.rej                                                                                                [ !! ]
 * ERROR: media-tv/plex-media-server-1.21.0-r1::plex-overlay failed (prepare phase):
 *   patch -p1  failed with /var/tmp/portage/media-tv/plex-media-server-1.21.0-r1/files/plexmediaserver.service.patch
 *
 * Call stack:
 *               ebuild.sh, line  125:  Called src_prepare
 *             environment, line 1463:  Called default
 *      phase-functions.sh, line  855:  Called default_src_prepare
 *      phase-functions.sh, line  920:  Called __eapi6_src_prepare
 *             environment, line  182:  Called eapply '/var/tmp/portage/media-tv/plex-media-server-1.21.0-r1/files/plexmediamanager.desktop.new.patch' '/var/tmp/portage/media-tv/plex-media-server-1.21.0-r1/files/plexmediaserver.service.patch'
 *             environment, line  555:  Called _eapply_patch '/var/tmp/portage/media-tv/plex-media-server-1.21.0-r1/files/plexmediaserver.service.patch'
 *             environment, line  493:  Called __helpers_die 'patch -p1  failed with /var/tmp/portage/media-tv/plex-media-server-1.21.0-r1/files/plexmediaserver.service.patch'
 *   isolated-functions.sh, line  112:  Called die
 * The specific snippet of code:
 *              die "$@"
 *
 * If you need support, post the output of `emerge --info '=media-tv/plex-media-server-1.21.0-r1::plex-overlay'`,
 * the complete build log and the output of `emerge -pqv '=media-tv/plex-media-server-1.21.0-r1::plex-overlay'`.
 * The complete build log is located at '/var/tmp/portage/media-tv/plex-media-server-1.21.0-r1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-tv/plex-media-server-1.21.0-r1/temp/environment'.
 * Working directory: '/var/tmp/portage/media-tv/plex-media-server-1.21.0-r1/work'
 * S: '/var/tmp/portage/media-tv/plex-media-server-1.21.0-r1/work'

**Comment by JonnoN** [comment]
` +export PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION="$${GENTOO_PROFILE#.*/profiles/}"; `

^ perhaps there is an extra $ in there?

**Comment by comio** [comment]
I don't see any issue.
Open again if you need.

**Comment by JonnoN** [comment]
It's still failing.

` * plexmediaserver_1.21.1.3753-b452b403c_i386.deb BLAKE2B SHA512 size ;-) ...                                                                                                                              [ ok ]
>>> Unpacking source...
>>> Unpacking plexmediaserver_1.21.1.3753-b452b403c_i386.deb to /var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/work
>>> Unpacking data.tar.xz to /var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/work
>>> Source unpacked in /var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/work
>>> Preparing source in /var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/work ...
 * Applying plexmediamanager.desktop.new.patch ...                                                                                                                                                         [ ok ]
 * Applying plexmediaserver.service.patch ...
patching file usr/lib/plexmediaserver/lib/plexmediaserver.service
Hunk #1 FAILED at 27.
1 out of 1 hunk FAILED -- saving rejects to file usr/lib/plexmediaserver/lib/plexmediaserver.service.rej                                                                                                   [ !! ]
 * ERROR: media-tv/plex-media-server-1.21.1.3753::plex-overlay failed (prepare phase):
 *   patch -p1  failed with /var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/files/plexmediaserver.service.patch
 * 
 * Call stack:
 *               ebuild.sh, line  125:  Called src_prepare
 *             environment, line 1471:  Called default
 *      phase-functions.sh, line  855:  Called default_src_prepare
 *      phase-functions.sh, line  920:  Called __eapi6_src_prepare
 *             environment, line  190:  Called eapply '/var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/files/plexmediamanager.desktop.new.patch' '/var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/files/plexmediaserver.service.patch'
 *             environment, line  563:  Called _eapply_patch '/var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/files/plexmediaserver.service.patch'
 *             environment, line  501:  Called __helpers_die 'patch -p1  failed with /var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/files/plexmediaserver.service.patch'
 *   isolated-functions.sh, line  112:  Called die
 * The specific snippet of code:
 *   		die "$@"
 * 
 * If you need support, post the output of `emerge --info '=media-tv/plex-media-server-1.21.1.3753::plex-overlay'`,
 * the complete build log and the output of `emerge -pqv '=media-tv/plex-media-server-1.21.1.3753::plex-overlay'`.
 * The complete build log is located at '/var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/temp/environment'.
 * Working directory: '/var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/work'
 * S: '/var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/work'

>>> Failed to emerge media-tv/plex-media-server-1.21.1.3753, Log file:

>>>  '/var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/temp/build.log'

 * Messages for package media-tv/plex-media-server-1.21.1.3753:

 * ERROR: media-tv/plex-media-server-1.21.1.3753::plex-overlay failed (prepare phase):
 *   patch -p1  failed with /var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/files/plexmediaserver.service.patch
 * 
 * Call stack:
 *               ebuild.sh, line  125:  Called src_prepare
 *             environment, line 1471:  Called default
 *      phase-functions.sh, line  855:  Called default_src_prepare
 *      phase-functions.sh, line  920:  Called __eapi6_src_prepare
 *             environment, line  190:  Called eapply '/var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/files/plexmediamanager.desktop.new.patch' '/var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/files/plexmediaserver.service.patch'
 *             environment, line  563:  Called _eapply_patch '/var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/files/plexmediaserver.service.patch'
 *             environment, line  501:  Called __helpers_die 'patch -p1  failed with /var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/files/plexmediaserver.service.patch'
 *   isolated-functions.sh, line  112:  Called die
 * The specific snippet of code:
 *   		die "$@"
 * 
 * If you need support, post the output of `emerge --info '=media-tv/plex-media-server-1.21.1.3753::plex-overlay'`,
 * the complete build log and the output of `emerge -pqv '=media-tv/plex-media-server-1.21.1.3753::plex-overlay'`.
 * The complete build log is located at '/var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/temp/environment'.
 * Working directory: '/var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/work'
 * S: '/var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/work'
packrat1 ~ # cd /var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/work/
packrat1 /var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/work # cat usr/lib/plexmediaserver/lib/plexmediaserver.service.rej
--- usr/lib/plexmediaserver/lib/plexmediaserver.service.old	2020-11-22 18:18:21.258165393 +0100
+++ usr/lib/plexmediaserver/lib/plexmediaserver.service	2020-11-22 18:18:35.864602444 +0100
@@ -27,7 +27,8 @@
 export PLEX_MEDIA_SERVER_INFO_VENDOR="$(grep ^NAME= /etc/os-release | awk -F= "{print \\$2}" | tr -d \\" )"; \
 export PLEX_MEDIA_SERVER_INFO_DEVICE="PC"; \
 export PLEX_MEDIA_SERVER_INFO_MODEL="$(uname -m)"; \
-export PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION="$(grep ^VERSION= /etc/os-release | awk -F= "{print \\$2}" | tr -d \\" )"; \
+export GENTOO_PROFILE="`readlink /etc/portage/make.profile`"; \
+export PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION="$${GENTOO_PROFILE#.*/profiles/}"; \
 exec "/usr/lib/plexmediaserver/Plex Media Server"'
 Type=simple
 User=plex

packrat1 /var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/work # ls -l usr/lib/plexmediaserver/lib/plexmediaserver.service.old
ls: cannot access 'usr/lib/plexmediaserver/lib/plexmediaserver.service.old': No such file or directory
packrat1 /var/tmp/portage/media-tv/plex-media-server-1.21.1.3753/work # ls -l usr/lib/plexmediaserver/lib/plexmediaserver.service
-rw-r--r-- 1 portage portage 1764 Dec  8 07:58 usr/lib/plexmediaserver/lib/plexmediaserver.service


`

thanks
[build.log](https://github.com/comio/plex-overlay/files/5663271/build.log)
[emerge_info.txt](https://github.com/comio/plex-overlay/files/5663272/emerge_info.txt)
[emerge-pqv.txt](https://github.com/comio/plex-overlay/files/5663273/emerge-pqv.txt)
[environment.txt](https://github.com/comio/plex-overlay/files/5663275/environment.txt)

**Comment by Bigun** [comment]
Still failing here as well, trying to update to 1.21.2.3978.  Same error:

`patching file usr/lib/plexmediaserver/lib/plexmediaserver.service
Hunk #1 FAILED at 27.
1 out of 1 hunk FAILED -- saving rejects to file usr/lib/plexmediaserver/lib/plexmediaserver.service.rej                                                                                                                              [ !! ]
 * ERROR: media-tv/plex-media-server-1.21.2.3978::plex-overlay failed (prepare phase):
 *   patch -p1  failed with /var/tmp/portage/media-tv/plex-media-server-1.21.2.3978/files/plexmediaserver.service.patch
 *
 * Call stack:
 *               ebuild.sh, line  125:  Called src_prepare
 *             environment, line 1466:  Called default
 *      phase-functions.sh, line  855:  Called default_src_prepare
 *      phase-functions.sh, line  920:  Called __eapi6_src_prepare
 *             environment, line  181:  Called eapply '/var/tmp/portage/media-tv/plex-media-server-1.21.2.3978/files/plexmediamanager.desktop.new.patch' '/var/tmp/portage/media-tv/plex-media-server-1.21.2.3978/files/plexmediaserver.service.patch'
 *             environment, line  557:  Called _eapply_patch '/var/tmp/portage/media-tv/plex-media-server-1.21.2.3978/files/plexmediaserver.service.patch'
 *             environment, line  495:  Called __helpers_die 'patch -p1  failed with /var/tmp/portage/media-tv/plex-media-server-1.21.2.3978/files/plexmediaserver.service.patch'
 *   isolated-functions.sh, line  112:  Called die
 * The specific snippet of code:
 *              die "$@"
`

**Comment by Bigun** [comment]
@JonnoN @rugubara 

What is your ACCEPT_KEYWORDS set to?

**Comment by Bigun** [comment]
@comio Can you re-open, there's clearly still an issue.

**Comment by comio** [comment]
I think that it depends on your architecture. Maybe x86 release is different amd64. Why are you still using x86 target?

**Comment by Bigun** [comment]
> 
> 
> I think that it depends on your architecture. Maybe x86 release is different amd64. Why are you still using x86 target?

It was decision made nearly 7-8 years ago, and at the time a lot of 64 bit builds were unstable.  A lot has changed since then, and I'm painfully aware that nearly every system is a native 64-bit build and I need to change, but it's a matter of how much time I'm willing to give to the task, and I'm just not ready yet.  Maybe when I retire the hardware and go to something new.

**Comment by comio** [comment]
```
diff -ura 32bit/usr/lib/plexmediaserver/lib/plexmediaserver.init 64bit/usr/lib/plexmediaserver/lib/plexmediaserver.init
--- 32bit/usr/lib/plexmediaserver/lib/plexmediaserver.init	2021-02-08 20:36:48.000000000 +0100
+++ 64bit/usr/lib/plexmediaserver/lib/plexmediaserver.init	2021-02-08 20:34:39.000000000 +0100
@@ -151,7 +151,6 @@
     export PLEX_MEDIA_SERVER_TMPDIR="$PlexTempDir"
     export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR="$PlexAppSuppDir"
 
-    export LD_LIBRARY_PATH="${PLEX_MEDIA_SERVER_HOME}/lib"
     export TMPDIR="${PlexTempDir}"
     ulimit -s "$PLEX_MEDIA_SERVER_MAX_STACK_SIZE"
 
diff -ura 32bit/usr/lib/plexmediaserver/lib/plexmediaserver.service 64bit/usr/lib/plexmediaserver/lib/plexmediaserver.service
--- 32bit/usr/lib/plexmediaserver/lib/plexmediaserver.service	2021-02-08 20:36:48.000000000 +0100
+++ 64bit/usr/lib/plexmediaserver/lib/plexmediaserver.service	2021-02-08 20:34:39.000000000 +0100
@@ -28,7 +28,6 @@
 export PLEX_MEDIA_SERVER_INFO_DEVICE="PC"; \
 export PLEX_MEDIA_SERVER_INFO_MODEL="$(uname -m)"; \
 export PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION="$(grep ^VERSION= /etc/os-release | awk -F= "{print \\$2}" | tr -d \\" )"; \
-export LD_LIBRARY_PATH=/usr/lib/plexmediaserver/lib; \
 exec "/usr/lib/plexmediaserver/Plex Media Server"'
 Type=simple
```

**Comment by comio** [comment]
@Bigun Can you give a try?

thanks,

luigi

**Comment by Bigun** [comment]
@comio 

Merged successfully

**Comment by comio** [comment]
great

**Comment by comio** [comment]
BTW, I have not way to test the 32bit installation.

**Comment by JonnoN** [comment]
works for me, thank you!

(I'm on 32 bit because it's an old VM I haven't bothered to replace)
