### ISSUE TITLE
x86 - v1.23.1.4528 - patch failed

### ISSUE THREAD

**Issue by Bigun** [comio/plex-overlay#28]
` * Applying plexmediaserver.service.x86.patch ...
patching file usr/lib/plexmediaserver/lib/plexmediaserver.service
Hunk #1 FAILED at 27.
1 out of 1 hunk FAILED -- saving rejects to file usr/lib/plexmediaserver/lib/plexmediaserver.service.rej                                                                                                                                                 [ !! ]
 * ERROR: media-tv/plex-media-server-1.23.1.4528::plex-overlay failed (prepare phase):
 *   patch -p1  failed with /var/tmp/portage/media-tv/plex-media-server-1.23.1.4528/files/plexmediaserver.service.x86.patch
 *
 * Call stack:
 *               ebuild.sh, line  125:  Called src_prepare
 *             environment, line 1464:  Called eapply '/var/tmp/portage/media-tv/plex-media-server-1.23.1.4528/files/plexmediaserver.service.x86.patch'
 *             environment, line  556:  Called _eapply_patch '/var/tmp/portage/media-tv/plex-media-server-1.23.1.4528/files/plexmediaserver.service.x86.patch'
 *             environment, line  494:  Called __helpers_die 'patch -p1  failed with /var/tmp/portage/media-tv/plex-media-server-1.23.1.4528/files/plexmediaserver.service.x86.patch'
 *   isolated-functions.sh, line  112:  Called die
 * The specific snippet of code:
 *              die "$@"
`

**Comment by comio** [comment]
Can you attach the .rej file?
