### ISSUE TITLE
Update to 1.24: usr/sbin/start_pms does not exist

### ISSUE THREAD

**Issue by drt1** [comio/plex-overlay#29]
After update to 1.24 the /etc/conf.d/plexmediaserver config file has changed and a new param was added with default value:

PLEX_SCRIPT="/usr/sbin/start_pms"

but, there is no such file.
Therefore pms does not start.

do you have an idea how to adjust the config file?
Or may you put version 1.23 back in the tree, so affected users can easily downgrade?

thank you!

**Comment by comio** [comment]
sorry, I synced with portage scripts.
Can you give a try?

thanks,

luigi

**Comment by drt1** [comment]
Thanks for the quick retry.

Now the default value has changed:
`PLEX_SCRIPT=„/usr/lib/plexmediaserver/Plex Media Server“`

but unfortunately it seems to have issues with the whitespaces in path:
`start-stop-daemon: /usr/lib/plexmediaserver/Plex does not exist`

I tried single quotes or escaping the spaces with backslashes, but no luck.
Any idea?

**Comment by drt1** [comment]
Alright, last parts were my fault, now everything runs again, thank you for the quick fix!
