### ISSUE TITLE
Verify failed

### ISSUE THREAD

**Issue by lucasmr** [comio/plex-overlay#3]
2019-12-22 21:14:27 (314 KB/s) - ‘/usr/portage/distfiles/web-client-desktop-3.104.2-1b12c68.tar.xz.__download__’ saved [3708140/3708140]

!!! Fetched file: web-client-desktop-3.104.2-1b12c68.tar.xz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      3708140
!!! Expected: 3708444
Refetching... File renamed to '/usr/portage/distfiles/web-client-desktop-3.104.2-1b12c68.tar.xz._checksum_failure_.0o436bjj'

!!! Couldn't download 'web-client-desktop-3.104.2-1b12c68.tar.xz'. Aborting.
 * Fetch failed for 'media-tv/plex-media-player-2.47.0.1035', Log file:
 *  '/var/tmp/portage/media-tv/plex-media-player-2.47.0.1035/temp/build.log'

Failed to emerge media-tv/plex-media-player-2.47.0.1035

**Comment by comio** [comment]
The file changes at every download... can you try the "download" option?
