### ISSUE TITLE
Orphaned files

### ISSUE THREAD

**Issue by drt1** [comio/plex-overlay#30]
Hey,

I noticed orphaned files when running revdep-rebuild.
Build 4931-r2 merges fine, but on next run of revdep-rebuild the same orphan files are reported.

`revdep-rebuild
 * Checking dynamic linking consistency
 * Assign files to packages

 !!! Broken orphaned files: No installed package was found for the following:
* /usr/lib/plexmediaserver/Plex Relay
* /usr/lib/plexmediaserver/Plex Commercial Skipper
* /usr/lib/plexmediaserver/Plex DLNA Server
* /usr/lib/plexmediaserver/Plex Media Scanner
* /usr/lib/plexmediaserver/Plex Transcoder
* /usr/lib/plexmediaserver/Plex Tuner Service
* /usr/lib/plexmediaserver/Plex SQLite
* /usr/lib/plexmediaserver/Plex Media Server
* /usr/lib/plexmediaserver/Plex Media Fingerprinter
* /usr/lib/plexmediaserver/Plex Script Host

emerge  --oneshot --complete-graph=y media-tv/plex-media-server:0
Calculating dependencies... done! `

No crucial issue, but I wanted to let you know.
Thanks for the awesome work!

**Comment by Avalanchee** [comment]
Same issue here.
I noticed it happens after some packages are removed by emerge -c.

**Comment by comio** [comment]
It's an issue of the new revdep-rebuild try with revdep-rebuild.sh

**Comment by jonesmz** [comment]
Is there an existing bug report for this issue against the new revdep-rebuild?
