### ISSUE TITLE
Ebuild missing

### ISSUE THREAD

**Issue by AnonymousRetard** [comio/plex-overlay#31]
I think you forgot to add the new ebuild to git, I can see you added a new ebuild to the manifest file but it's not listed here on git either. Trying to update plex-media-server throws this error message:

`!!! A file listed in the Manifest could not be found: /var/lib/layman/plex-overlay/media-tv/plex-media-server/plex-media-server-1.24.4.5081.ebuild`

**Comment by comio** [comment]
My apoloies, I forgot a file. Should be fixed now.

ciao
