### ISSUE TITLE
Filesize does not match recorded size for plex-media-player

### ISSUE THREAD

**Issue by minorsecond** [comio/plex-overlay#33]
When trying to install Plex Media Player from the plex-overlay overlay, I'm presented with the following error:

```
!!! Fetched file: web-client-desktop-4.29.2-e50e175.tar.xz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      4048344
!!! Expected: 4063292
```

I'm trying to merge plex-media-player-2.58.1

**Comment by comio** [comment]
Closed by 9ace618483adf6f4a9344769ce09a6a1138443cd
