### ISSUE TITLE
(TRACKING) Plex removed start_pms script

### ISSUE THREAD

**Issue by comio** [comio/plex-overlay#8]
Plex removed start_pms script and this will break openrc script.

1.19.1 ebuild will deploy an own copy of start_pms script.

Q: Can we drop openrc support?

**Comment by torre76** [comment]
Hi @comio,

Currently my _headless_ server is using _OpenRC_.
Personally, I do not like _systemd_ at all (even if I use it extensively at work). 

Please continue to deploy the copy of `start_pms` script.

**Comment by comio** [comment]
@torre76 I will keep the script but I cannot test on openrc. Can you provide me feedback when something went wrong?

**Comment by torre76** [comment]
For sure!
In case it is not working, I will create a PR with fixes.

**Comment by torre76** [comment]
Just updated PMS, script is working.

**Comment by Gatak** [comment]
Thanks for keeping OpenRC support. A lot of Gentooers still use OpenRC. Including me :D
